### ISSUE TITLE
Faster Clean CCL

### ISSUE THREAD

**Issue by william-silversmith** [yhzhao343/brainbraille_helpers#1]
Hi! I was nosing around to see how people are using cc3d and I thought your project was really cool! I took a look at how cc3d was being used, and I saw some tricks that could be applied to speed up the function a lot in some circumstances (it might be fine for you as is though). I think I'll add a `remove_dust` function sometime in the near future as lots of people seem to be doing that. Here's some code that you can use if that function is being a bottleneck:

Apologies if this code isn't needed or wanted.

```python
def connected_component_clean(activation_mask, discard_size_ratio = 0.5):
  activation_mask_cc, N = cc3d.connected_components(activation_mask, return_N=True)
  stats = cc3d.statistics(activation_mask_cc)
  mask_sizes = stats["voxel_counts"][1:]
  discard_size_threshold = int(np.max(mask_sizes) * discard_size_ratio)

  runs = cc3d.runs(activation_mask_cc)

  for label in range(1,N+1):
    if mask_sizes[label-1] <= discard_size_threshold:
      cc3d.erase(runs[label], activation_mask_cc)

  return activation_mask_cc > 0
```

https://github.com/yhzhao343/brainbraille_helpers/blob/ec9d94557a3b25281e6fd27b356421dc8565343c/src/brainbraille_helpers/roi.py#L7-L20

**Comment by yhzhao343** [comment]
Thanks for the suggestion! I ran some initial tests, and it seems your implementation is returning different results. I will run more test and investigate more when I get a chance.

**Comment by william-silversmith** [comment]
Sorry if it's not extensively tested! The general idea should work. I'm
working on a version with more testing for cc3d.dust which will take a
voxel threshold. If it's not super easy to get it working, please just
ignore it. I don't want to waste your time.

**Comment by yhzhao343** [comment]
Actually, my bad. I think your code returns the same results. I was playing with the indices when I copied your code over and missed the label index. I benchmarked yours and my original a bit and made some changes. Here is my latest and fastest implementation:
```python
def connected_component_clean(activation_mask, discard_size_ratio = 0.5):
  activation_mask_cc, N = cc3d.connected_components(activation_mask, return_N=True)
  components_list = np.arange(1, N+1)
  mask_list = np.array([activation_mask_cc == c for c in components_list])
  mask_sizes = np.array([m.sum() for m in mask_list])
  max_mask_size = np.max(mask_sizes)
  discard_size_threshold = int(max_mask_size * discard_size_ratio)
  return np.any(mask_list[mask_sizes >= discard_size_threshold], axis=0)
```
Edit: I think the performance is probably dataset dependent. At least for the fMRI data I am currently analyzing, the code above seems to have the best performance.

**Comment by william-silversmith** [comment]
Interesting! The typical volumes I work with have little noise and are large (e.g. 512x512x512). If there's a lot of noise in your volumes, cc3d.runs will be somewhat slow and use a lot of memory. This solution potentially uses a lot of memory and becomes slow if there are a large number of components (hungreds, thousands) but if it's a small number it's fine. Glad you were able to find a good solution for your problem! Code similar to what I shared will be present in cc3d 3.7.0 sometime today.

**Comment by yhzhao343** [comment]
My data are usually 97x115x97 and has <20 components, so I guess it is fairly clean. Good point on the memory consumption. My original implementation's memory does not scale up as the number of components increases. So, I am reverting to that implementation with some tweaks. Previously, the np.unique costs a lot. I am happy you showed me the return_N trick so I don't need to do that. Also, turns out np.count_nonzero is a lot faster than np.sum for counting Trues in a boolean array. With these changes, I got my fastest implementation yet (>3x speed improvement than the original code on my data).
```python
def connected_component_clean(activation_mask, discard_size_ratio = 0.5):
  cleaned_activation_mask = np.zeros(activation_mask.shape, dtype=bool)
  activation_mask_cc, N = cc3d.connected_components(activation_mask, return_N=True)
  components_list = range(1, N+1)
  mask_sizes = [np.count_nonzero(activation_mask_cc == c) for c in components_list]
  max_mask_size = np.max(mask_sizes) 
  discard_size_threshold = int(max_mask_size * discard_size_ratio) 
  for c, c_component_size in zip(components_list, mask_sizes): 
    if c_component_size > discard_size_threshold: 
      component_mask = (activation_mask_cc == c) 
      cleaned_activation_mask = np.logical_or(cleaned_activation_mask, component_mask) 
  return cleaned_activation_mask
```
Thank you for sending me down this optimization path, and of course thank you for publishing the cc3d library in the first place. Made my life a lot easier!

**Comment by william-silversmith** [comment]
Glad it was helpful! As a parting word, I think you may (now or in the future) be interested in my other library https://github.com/seung-lab/fastremap which has a faster implementation of `np.unique`. For cc3d, you only need to run `np.max` to get N if you don't use `return_N` though. <3

**Comment by yhzhao343** [comment]
Thank you! I will definitely check it out when the need arises.
Closing the issue.
